// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(HRDBContext))]
    [Migration("20260221141725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entites.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DepartmentDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentCode = "IT",
                            DepartmentDescription = "Infrastructure & Software Development",
                            DepartmentName = "Information Technology"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentCode = "HR",
                            DepartmentDescription = "Talent Management & Employee Relations",
                            DepartmentName = "Human Resources"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentCode = "FIN",
                            DepartmentDescription = "Financial Planning & Payroll",
                            DepartmentName = "Finance & Accounting"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentCode = "S&M",
                            DepartmentDescription = "Revenue Generation & Brand Awareness",
                            DepartmentName = "Sales & Marketing"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentCode = "OPS",
                            DepartmentDescription = "Core Business Operations & Logistics",
                            DepartmentName = "Operations"
                        });
                });

            modelBuilder.Entity("Domain.Entites.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmployeeCurrentAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmployeeFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("EmployeeGender")
                        .HasColumnType("tinyint");

                    b.Property<string>("EmployeeLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmployeeNationalityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EmployeeResignationDate")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeSecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeThirdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsForeign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.ComplexProperty<Dictionary<string, object>>("EmployeeBirthDate", "Domain.Entites.Employee.EmployeeBirthDate#BirthDate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("Value")
                                .HasColumnType("date")
                                .HasColumnName("BirthDate");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("EmployeeNationalNumber", "Domain.Entites.Employee.EmployeeNationalNumber#NationalNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("nvarchar(14)")
                                .HasColumnName("NationalNumber");
                        });

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("EmployeeNationalityId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Domain.Entites.EmployeeEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.ComplexProperty<Dictionary<string, object>>("Value", "Domain.Entites.EmployeeEmail.Value#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Email");
                        });

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("EmployeeEmails", (string)null);
                });

            modelBuilder.Entity("Domain.Entites.EmployeePhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.ComplexProperty<Dictionary<string, object>>("Value", "Domain.Entites.EmployeePhone.Value#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PhoneNumber");
                        });

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("EmployeePhones", (string)null);
                });

            modelBuilder.Entity("Domain.Entites.EmployeeWorkInfo", b =>
                {
                    b.Property<int>("EmployeeWorkInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeWorkInfoId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("JobTitleLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeWorkInfoId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobTitleLevelId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("EmployeeId", "IsCurrent")
                        .IsUnique()
                        .HasDatabaseName("IX_Employee_WorkInfo_Current_Unique")
                        .HasFilter("[IsCurrent] = 1");

                    b.ToTable("EmployeeWorkInfo", (string)null);
                });

            modelBuilder.Entity("Domain.Entites.JobGrade", b =>
                {
                    b.Property<int>("JobGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobGradeId"));

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("JobGradeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LevelDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("JobGradeId");

                    b.HasIndex("GradeCode")
                        .IsUnique();

                    b.HasIndex("JobGradeName")
                        .IsUnique();

                    b.HasIndex("Weight")
                        .IsUnique();

                    b.ToTable("JobGrades", (string)null);

                    b.HasData(
                        new
                        {
                            JobGradeId = 1,
                            GradeCode = "G1",
                            JobGradeName = "Junior Level",
                            LevelDescription = "Entry level for fresh graduates",
                            Weight = 100
                        },
                        new
                        {
                            JobGradeId = 2,
                            GradeCode = "G2",
                            JobGradeName = "Mid Level",
                            LevelDescription = "Individual contributor with experience",
                            Weight = 250
                        },
                        new
                        {
                            JobGradeId = 3,
                            GradeCode = "G3",
                            JobGradeName = "Senior Level",
                            LevelDescription = "Subject matter expert",
                            Weight = 450
                        },
                        new
                        {
                            JobGradeId = 4,
                            GradeCode = "G4",
                            JobGradeName = "Team Lead",
                            LevelDescription = "Technical or functional leadership",
                            Weight = 700
                        },
                        new
                        {
                            JobGradeId = 5,
                            GradeCode = "G5",
                            JobGradeName = "Management",
                            LevelDescription = "Strategic leadership and decision making",
                            Weight = 1000
                        });
                });

            modelBuilder.Entity("Domain.Entites.JobTitle", b =>
                {
                    b.Property<int>("JobTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTitleId"));

                    b.Property<string>("JobTitleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("JobTitleDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobTitleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobTitleId");

                    b.HasIndex("JobTitleCode")
                        .IsUnique();

                    b.HasIndex("JobTitleName")
                        .IsUnique();

                    b.ToTable("JobTitles", (string)null);

                    b.HasData(
                        new
                        {
                            JobTitleId = 1,
                            JobTitleCode = "BEDEV",
                            JobTitleDescription = "Developing scalable backend systems",
                            JobTitleName = "Backend .NET Developer"
                        },
                        new
                        {
                            JobTitleId = 2,
                            JobTitleCode = "HRGEN",
                            JobTitleDescription = "Handling day-to-day HR operations",
                            JobTitleName = "HR Generalist"
                        },
                        new
                        {
                            JobTitleId = 3,
                            JobTitleCode = "ACC",
                            JobTitleDescription = "Managing company accounts and taxes",
                            JobTitleName = "Financial Accountant"
                        },
                        new
                        {
                            JobTitleId = 4,
                            JobTitleCode = "SYSAD",
                            JobTitleDescription = "Managing server infrastructure",
                            JobTitleName = "System Administrator"
                        },
                        new
                        {
                            JobTitleId = 5,
                            JobTitleCode = "OPSM",
                            JobTitleDescription = "Overseeing operational workflows",
                            JobTitleName = "Operations Manager"
                        });
                });

            modelBuilder.Entity("Domain.Entites.JobTitleLevel", b =>
                {
                    b.Property<int>("JobTitleLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTitleLevelId"));

                    b.Property<int>("JobGradeId")
                        .HasColumnType("int");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("int");

                    b.HasKey("JobTitleLevelId");

                    b.HasIndex("JobGradeId");

                    b.HasIndex("JobTitleId", "JobGradeId")
                        .IsUnique();

                    b.ToTable("JobTitleLevels", (string)null);

                    b.HasData(
                        new
                        {
                            JobTitleLevelId = 1,
                            JobGradeId = 1,
                            JobTitleId = 1
                        },
                        new
                        {
                            JobTitleLevelId = 2,
                            JobGradeId = 2,
                            JobTitleId = 1
                        },
                        new
                        {
                            JobTitleLevelId = 3,
                            JobGradeId = 3,
                            JobTitleId = 1
                        },
                        new
                        {
                            JobTitleLevelId = 4,
                            JobGradeId = 4,
                            JobTitleId = 1
                        },
                        new
                        {
                            JobTitleLevelId = 5,
                            JobGradeId = 1,
                            JobTitleId = 2
                        },
                        new
                        {
                            JobTitleLevelId = 6,
                            JobGradeId = 2,
                            JobTitleId = 2
                        },
                        new
                        {
                            JobTitleLevelId = 7,
                            JobGradeId = 4,
                            JobTitleId = 5
                        },
                        new
                        {
                            JobTitleLevelId = 8,
                            JobGradeId = 5,
                            JobTitleId = 5
                        });
                });

            modelBuilder.Entity("Domain.Entites.Nationality", b =>
                {
                    b.Property<int>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NationalityId"));

                    b.Property<string>("NationalityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NationalityId");

                    b.HasIndex("NationalityName")
                        .IsUnique();

                    b.ToTable("Nationalities", (string)null);

                    b.HasData(
                        new
                        {
                            NationalityId = 1,
                            NationalityName = "Egyptian"
                        },
                        new
                        {
                            NationalityId = 2,
                            NationalityName = "Saudi"
                        },
                        new
                        {
                            NationalityId = 3,
                            NationalityName = "Emirati"
                        },
                        new
                        {
                            NationalityId = 4,
                            NationalityName = "Jordanian"
                        },
                        new
                        {
                            NationalityId = 5,
                            NationalityName = "American"
                        });
                });

            modelBuilder.Entity("Domain.Entites.PendingAdminAction", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<byte>("ActionType")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProcessNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int");

                    b.Property<string>("RequestReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("int");

                    b.HasKey("ActionId");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("TargetUserId");

                    b.ToTable("PendingAdminActions", (string)null);
                });

            modelBuilder.Entity("Domain.Entites.Token", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReplacedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("TokenId");

                    b.HasIndex("ReplacedById");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entites.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserPasswordHashing")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PasswordHash");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint");

                    b.HasKey("UserId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entites.UserLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("LogTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogs", (string)null);
                });

            modelBuilder.Entity("Domain.Entites.Employee", b =>
                {
                    b.HasOne("Domain.Entites.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("EmployeeNationalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("Domain.Entites.EmployeeEmail", b =>
                {
                    b.HasOne("Domain.Entites.Employee", null)
                        .WithMany("Emails")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entites.EmployeePhone", b =>
                {
                    b.HasOne("Domain.Entites.Employee", null)
                        .WithMany("Phones")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entites.EmployeeWorkInfo", b =>
                {
                    b.HasOne("Domain.Entites.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Employee", null)
                        .WithMany("WorkInfoHistory")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entites.JobTitleLevel", "JobTitleLevel")
                        .WithMany()
                        .HasForeignKey("JobTitleLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("JobTitleLevel");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Domain.Entites.JobTitleLevel", b =>
                {
                    b.HasOne("Domain.Entites.JobGrade", "JobGrade")
                        .WithMany()
                        .HasForeignKey("JobGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobGrade");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("Domain.Entites.PendingAdminAction", b =>
                {
                    b.HasOne("Domain.Entites.User", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entites.User", "Requestor")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entites.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Processor");

                    b.Navigation("Requestor");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Domain.Entites.Token", b =>
                {
                    b.HasOne("Domain.Entites.Token", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entites.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entites.User", b =>
                {
                    b.HasOne("Domain.Entites.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("Domain.Entites.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entites.UserLog", b =>
                {
                    b.HasOne("Domain.Entites.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entites.Employee", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Phones");

                    b.Navigation("WorkInfoHistory");
                });

            modelBuilder.Entity("Domain.Entites.User", b =>
                {
                    b.Navigation("Tokens");

                    b.Navigation("UserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
